name: reddit-scraper

on:
  schedule:
    - cron: '38 * * * *'

jobs:
  reddit-scraper-daily-nba-top10:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install related packages
        run: Rscript -e 'install.packages(c("tidyverse", "httr", "jsonlite", "RedditExtractoR"), dependencies = TRUE)'
      - name: Start to scrape data
        run: Rscript reddit-nba-scraper/cron-job.r
