name: reddit-scraper

on:
    schedule:
        - cron: '2 21 * * *'

jobs:
    reddit-scraper-daily-nba-top10:
        runs-on: macOS-latest
        steps:
            - uses: actions/checkout@v2
            - uses: r-lib/actions/setup-r@master
            - name: Install related packages
              run: Rscript -e 'install.packages(c("tidyverse", "RedditExtractoR", "tidytext"), dependencies = TRUE)'
            - name: Start to scrape data
              run: Rscript reddit-nba-scraper/cron-job.r
            - name: Git Auto Commit
              uses: stefanzweifel/git-auto-commit-action@v4.12.0
